=== pedrorpmoura/DWeb2019/TPC2/PR.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- PR -->
<!ELEMENT pr (header, workteam, abstract, deliverables, date) >


<!-- Header -->
<!ELEMENT header (keyname, title, subtitle?, begin-date, end-date, supervisor) >
<!ELEMENT keyname (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT begin-date (#PCDATA) >
<!ELEMENT end-date (#PCDATA) >
<!ELEMENT supervisor (#PCDATA) >

<!ATTLIST supervisor
            link CDATA #FIXED "http://www4.di.uminho.pt/~jcr/" >


<!-- Workteam -->
<!ELEMENT workteam (element+) >
<!ELEMENT element (name, number, email, git?) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT number (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT git (#PCDATA) >

<!ATTLIST git 
            link CDATA #REQUIRED >


<!-- Abstract -->
<!ELEMENT abstract (#PCDATA|bold|italic|ref)* >
<!ELEMENT bold (#PCDATA) >
<!ELEMENT italic (#PCDATA) >
<!ELEMENT ref (#PCDATA) >

<!ATTLIST ref
            link CDATA #REQUIRED >


<!-- Deliverables -->
<!ELEMENT deliverables (deliverable*) >
<!ELEMENT deliverable (#PCDATA) >

<!ATTLIST deliverable
            link CDATA #REQUIRED >
            
            
<!-- Date -->
<!ELEMENT date (#PCDATA) >

=== pedrorpmoura/DWeb2019/TPC2/PR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "PR.dtd">
<pr>
    <header>
        <keyname>TPC_2</keyname>
        <title>Resolução do TPC 2 da UC de Desencolvimento de Aplicações Web</title>
        <begin-date>28-09-2019</begin-date>
        <end-date>29-09-2019</end-date>
        <supervisor link="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
    </header>
    <workteam>
        <element>
            <name>Pedro Moura</name>
            <number>PG41094</number>
            <email>pg41094@alunos.uminho.pt</email>
        </element>
    </workteam>
    <abstract>
        Isto é a resolução do <bold>TPC 2</bold> da disciplina de <italic>DWEB2019</italic>.
        <ref link="kblabafiefohwdjwi">Página da Disciplina</ref>
    </abstract>
    <deliverables>
        <deliverable link=""></deliverable>
    </deliverables>
</pr>
